services:
  user-db:
    image: postgres
    container_name: main_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password_123
      POSTGRES_DB: usersdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  user-service:
    build: ./user-service
    container_name: user_service
    ports:
      - "8080:8080"
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      JWT_SECRET: supersecret
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Password_123
      DB_NAME: usersdb

  book-db:
    image: postgres
    container_name: book_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password_123
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    volumes:
      - book_data:/var/lib/postgresql
      - ./docker/book-postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  book-service:
    build: ./book-service
    container_name: book_service
    ports:
      - "8081:8081"
    depends_on:
      book-db:
        condition: service_healthy
    environment:
      JWT_SECRET: supersecret
      DB_HOST: book-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Password_123
      DB_NAME: booksdb

  gateway:
    build: ./gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - book-service
    environment:
      GATEWAY_AUTH_ENABLED: "true"
      USER_SERVICE_URL: "http://user-service:8080"
      BOOK_SERVICE_URL: "http://book-service:8081"
      AUTH_HS_SECRET: supersecret
      AUTH_ALGO: HS256
volumes:
  db_data:
  book_data:
